### ISSUE TITLE
Bonn neu schreiben

### ISSUE THREAD

**Issue by mattfullerton** [SebastianBerchtold/odm-catalogreaders#5]
neu schreiben, bzw. enger mit einer der anderen ckan API 3 städte integrieren
man kriegt eine liste von Ids über /data.json (erste eintrag ignorieren)
dann die details mit package_show

**Comment by mattfullerton** [comment]
fertig, oder?

**Comment by SebastianBerchtold** [comment]
Im Prinzip ja, aber ich sollte da nochmal drüberschaun.
Da scheint sich mehr geändert zu haben. Ich habe zwar 
einiges mit einbezogen, bin da aber nicht sehr ins Deail gegangen.

**Comment by mattfullerton** [comment]
Ich muss meine Änderungen rüber bringen

**Comment by SebastianBerchtold** [comment]
Mit Änderungen, meinst du die in ckanAPIv3.py in odm-datenerafassung? 
Da hast du auf jedenfall recht,  das ist so viel sauberer.
Aber Bonn spezifisch, hatte ich da einiges anders. Weil die daten einen sehr inhomogenen 
eindruck gemacht haben. Aber wie oben gesagt, war das auch nicht so perfekt.

Hattest du dir den Bonn reader nach der API änderung nochmal genauer angeschaut?

**Comment by mattfullerton** [comment]
Ach, du hast es doch geändert, nur in dem bisherigen Form gehalten? Dann ist schon OK, muss man nichts machen. Habe mich gewundert, warum es noch doch funktioniert ;-)
